version: 0.2

env:
  secrets-manager:
    DOKCERHUB_USERNAME: dockerhub:username
    DOKCERHUB_PASSWORD: dockerhub:password
  variables:
    IMAGE: rborovets/defibrillator-back
            
phases:
  pre_build:
    commands:
      - echo Logging in to Dockerhub...
      - sudo docker login -u $DOKCERHUB_USERNAME -p $DOKCERHUB_PASSWORD

  build:
    commands:
      - echo Build started on `date` && echo Building the Docker image...

      - echo $IMAGE && sudo docker build . -t $IMAGE
      - sudo docker run $IMAGE echo 'Running tests'
      - sudo docker run $IMAGE echo 'Running linters'

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - sudo docker push $IMAGE